### ISSUE TITLE
:visible class

### ISSUE THREAD

**Issue by gingersoulrecords** [gingersoulrecords/SoulMatch#3]
I recently found this fix on the jQuery match height github

https://github.com/liabru/jquery-match-height/issues/126

to ignore elements that were not visible. This is helpful with a SoulSections navigation bar, so I can equalize the heights of the elements, then use CSS to translate shorter elements to their container's center (thereby aligning all elements in a straight line). 

Can we add :visible to our matchheight selectors?

Thanks, 

DB

**Comment by ideag** [comment]
yeah, that is probably a good idea :)

**Comment by gingersoulrecords** [comment]
More on this: 

I'm using the :visible selector on a site. It works fine on page load, but when the window is resized, the matchheight function needs to be called again to recognize which elements are (now) visible and which elements are not. Otherwise, it breaks the functionality and considers an 'invisible' element's height in the matching equation. 

Can we please add a .resize() function to update the selectors, per https://github.com/liabru/jquery-match-height/issues/60#issuecomment-155913995 (they're using an ajax example but we can add this to window.resize() )?

Thx

DB
